modLoader="javafml"
loaderVersion="[2,)"
license="GNU GPL 3.0"
issueTrackerURL="https://github.com/Xing-C/ClassicAndSimpleStatusBars/issues"
[[mods]]
modId="classicandsimplestatusbars"
version="${version}"
displayName="CSSB"
logoFile="icon.png"
authors="XingChen"
description='''
Display vanilla values in a brand new way, not just health and hunger values,
but also support more Mods information, such as thirst and water content.
'''
[[dependencies.classicandsimplestatusbars]]
modId="neoforge"
required = true
versionRange="[1,)"
ordering="NONE"
side="BOTH"
[[dependencies.classicandsimplestatusbars]]
modId="minecraft"
required = true
versionRange="[1.20.1,1.20.5)"
ordering="NONE"
side="BOTH"
[[dependencies.classicandsimplestatusbars]]
modId = "architectury"
required = true
versionRange = "[11.0.1,)"
ordering = "AFTER"
side = "BOTH"
[[mixins]]
config = "classicandsimplestatusbars.mixins.json"